// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title AgriTrace
 * @notice Blockchain-Based Agricultural Supply Chain Transparency System
 * @dev Deploy on Ethereum Sepolia testnet or Polygon Mumbai.
 *      The MERN backend calls these functions via ethers.js in production.
 */
contract AgriTrace {

    // ── Enums ─────────────────────────────────────────────────────────────────
    enum Stage  { Farm, Processing, Distribution, Retail, Sold }
    enum Status { Active, Recalled, Expired, Sold }
    enum CheckStatus { Passed, Flagged, Rejected }

    // ── Structs ───────────────────────────────────────────────────────────────
    struct Checkpoint {
        Stage       stage;
        address     actor;
        string      location;
        string      notes;
        int16       temperature;   // °C × 10 (e.g., 45 = 4.5°C)
        uint8       humidity;      // %
        CheckStatus checkStatus;
        uint256     timestamp;
    }

    struct Batch {
        string      batchId;        // UUID from MongoDB
        string      productName;
        string      productType;
        uint256     quantity;       // in smallest unit (grams / ml)
        address     farmer;
        string      farmLocation;
        bool        organicCertified;
        Stage       currentStage;
        Status      batchStatus;
        uint8       integrityScore; // 0-100
        uint256     registeredAt;
        uint256     checkpointCount;
    }

    // ── State ─────────────────────────────────────────────────────────────────
    address public owner;

    mapping(string  => Batch)                    public batches;
    mapping(string  => Checkpoint[])             public checkpoints;
    mapping(address => bool)                     public authorizedActors;
    mapping(string  => bool)                     public batchExists;

    string[] public allBatchIds;

    // ── Events ────────────────────────────────────────────────────────────────
    event BatchRegistered(
        string indexed batchId,
        string productName,
        address indexed farmer,
        uint256 timestamp
    );
    event CheckpointAdded(
        string indexed batchId,
        Stage stage,
        address indexed actor,
        CheckStatus checkStatus,
        uint256 timestamp
    );
    event BatchRecalled(string indexed batchId, address by, uint256 timestamp);
    event ActorAuthorized(address indexed actor, bool status);

    // ── Modifiers ─────────────────────────────────────────────────────────────
    modifier onlyOwner()           { require(msg.sender == owner, "Not owner");           _; }
    modifier onlyAuthorized()      { require(authorizedActors[msg.sender] || msg.sender == owner, "Not authorized"); _; }
    modifier batchMustExist(string memory id) { require(batchExists[id], "Batch not found"); _; }

    // ── Constructor ───────────────────────────────────────────────────────────
    constructor() {
        owner = msg.sender;
        authorizedActors[msg.sender] = true;
    }

    // ── Actor Management ──────────────────────────────────────────────────────
    function authorizeActor(address actor, bool status) external onlyOwner {
        authorizedActors[actor] = status;
        emit ActorAuthorized(actor, status);
    }

    // ── Batch Registration ────────────────────────────────────────────────────
    /**
     * @notice Farmer registers a new produce batch (genesis block)
     * @param batchId     UUID generated by backend (MongoDB _id / uuid)
     * @param productName Name of the produce (e.g., "Basmati Rice")
     * @param productType Category string
     * @param quantity    Quantity in smallest unit
     * @param farmLocation String description of farm location
     * @param organicCertified Whether the batch is organic certified
     */
    function registerBatch(
        string memory batchId,
        string memory productName,
        string memory productType,
        uint256 quantity,
        string memory farmLocation,
        bool organicCertified
    ) external onlyAuthorized {
        require(!batchExists[batchId], "Batch already registered");
        require(bytes(productName).length > 0, "Product name required");
        require(quantity > 0, "Quantity must be > 0");

        batches[batchId] = Batch({
            batchId:          batchId,
            productName:      productName,
            productType:      productType,
            quantity:         quantity,
            farmer:           msg.sender,
            farmLocation:     farmLocation,
            organicCertified: organicCertified,
            currentStage:     Stage.Farm,
            batchStatus:      Status.Active,
            integrityScore:   100,
            registeredAt:     block.timestamp,
            checkpointCount:  0
        });

        // Record genesis checkpoint
        checkpoints[batchId].push(Checkpoint({
            stage:       Stage.Farm,
            actor:       msg.sender,
            location:    farmLocation,
            notes:       "Batch registered at farm",
            temperature: 0,
            humidity:    0,
            checkStatus: CheckStatus.Passed,
            timestamp:   block.timestamp
        }));

        batchExists[batchId] = true;
        allBatchIds.push(batchId);
        batches[batchId].checkpointCount = 1;

        emit BatchRegistered(batchId, productName, msg.sender, block.timestamp);
    }

    // ── Add Checkpoint ────────────────────────────────────────────────────────
    /**
     * @notice Supply chain actor adds a checkpoint to a batch
     * @param batchId     Target batch UUID
     * @param stage       Supply chain stage (0=Farm … 4=Sold)
     * @param location    Location string
     * @param notes       Quality / observation notes
     * @param temperature Temperature × 10 in int16 (e.g., 45 = 4.5°C)
     * @param humidity    Humidity percentage
     * @param checkStatus 0=Passed, 1=Flagged, 2=Rejected
     */
    function addCheckpoint(
        string memory batchId,
        Stage stage,
        string memory location,
        string memory notes,
        int16 temperature,
        uint8 humidity,
        CheckStatus checkStatus
    ) external onlyAuthorized batchMustExist(batchId) {
        Batch storage batch = batches[batchId];
        require(batch.batchStatus == Status.Active, "Batch is not active");

        checkpoints[batchId].push(Checkpoint({
            stage:       stage,
            actor:       msg.sender,
            location:    location,
            notes:       notes,
            temperature: temperature,
            humidity:    humidity,
            checkStatus: checkStatus,
            timestamp:   block.timestamp
        }));

        batch.checkpointCount++;

        // Update integrity score
        if (checkStatus == CheckStatus.Flagged)  {
            if (batch.integrityScore >= 10) batch.integrityScore -= 10;
            else batch.integrityScore = 0;
        } else if (checkStatus == CheckStatus.Rejected) {
            batch.integrityScore = 0;
            batch.batchStatus = Status.Recalled;
            emit BatchRecalled(batchId, msg.sender, block.timestamp);
        }

        // Advance stage
        if (checkStatus != CheckStatus.Rejected) {
            if (batch.currentStage == Stage.Farm)         batch.currentStage = Stage.Processing;
            else if (batch.currentStage == Stage.Processing) batch.currentStage = Stage.Distribution;
            else if (batch.currentStage == Stage.Distribution) batch.currentStage = Stage.Retail;
            else if (batch.currentStage == Stage.Retail)   batch.currentStage = Stage.Sold;
        }

        emit CheckpointAdded(batchId, stage, msg.sender, checkStatus, block.timestamp);
    }

    // ── Recall ────────────────────────────────────────────────────────────────
    function recallBatch(string memory batchId) external onlyOwner batchMustExist(batchId) {
        batches[batchId].batchStatus = Status.Recalled;
        batches[batchId].integrityScore = 0;
        emit BatchRecalled(batchId, msg.sender, block.timestamp);
    }

    // ── Read Functions ────────────────────────────────────────────────────────
    function getBatch(string memory batchId)
        external view batchMustExist(batchId)
        returns (Batch memory)
    {
        return batches[batchId];
    }

    function getCheckpoints(string memory batchId)
        external view batchMustExist(batchId)
        returns (Checkpoint[] memory)
    {
        return checkpoints[batchId];
    }

    function getCheckpointCount(string memory batchId)
        external view batchMustExist(batchId)
        returns (uint256)
    {
        return checkpoints[batchId].length;
    }

    function getTotalBatches() external view returns (uint256) {
        return allBatchIds.length;
    }

    function getAllBatchIds() external view returns (string[] memory) {
        return allBatchIds;
    }
}
